x-database-url: &database-url
  DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

services:
  # --- BASE DE DONNÉES ---
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '127.0.0.1:5435:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- MICROSERVICE AUTH ---
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: auth
    container_name: auth-service
    depends_on:
      - db
    environment:
      <<: *database-url
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      API_URL: ${API_URL}
      PORT_AUTH: ${PORT_AUTH}
      FRONTEND_URL: ${FRONTEND_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

  # --- MICROSERVICE APP ---
  app-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: app
    container_name: app-service
    depends_on:
      - db
      - auth-service
    environment:
      <<: *database-url
      PORT_APP: ${PORT_APP}
      PORT_AUTH: ${PORT_AUTH}
      FRONTEND_URL: ${FRONTEND_URL}
      CLOUDFRONT_DOMAIN: ${CLOUDFRONT_DOMAIN}
      INACTIVE_THRESHOLD_DAYS: ${INACTIVE_THRESHOLD_DAYS}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      STRIPE_PRODUCT_STARTER: ${STRIPE_PRODUCT_STARTER}
      STRIPE_PRODUCT_GROWTH: ${STRIPE_PRODUCT_GROWTH}
      STRIPE_PRODUCT_PRO: ${STRIPE_PRODUCT_PRO}

  # --- MICROSERVICE MEDIA ---
  media-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: media
    container_name: media-service
    depends_on:
      - db
    environment:
      <<: *database-url
      PORT_MEDIA: ${PORT_MEDIA}
      MEDIA_SECRET: ${MEDIA_SECRET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      S3_BUCKET: ${S3_BUCKET}
      CLOUDFRONT_DOMAIN: ${CLOUDFRONT_DOMAIN}

  # --- GATEWAY ---
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: gateway
    container_name: gateway-service
    depends_on:
      - db
      - auth-service
      - app-service
      - media-service
    environment:
      <<: *database-url
      PORT_GATEWAY: ${PORT_GATEWAY}
      PORT_AUTH: ${PORT_AUTH}
      PORT_APP: ${PORT_APP}
      PORT_MEDIA: ${PORT_MEDIA}
      MEDIA_SECRET: ${MEDIA_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
    ports:
      - '127.0.0.1:3080:${PORT_GATEWAY}'

volumes:
  postgres_data:
